urls:
  cookies: 'https://www.termsfeed.com/live/8eb23539-d8ea-4438-b0fc-c6675f8d4843'
  privacy_policy: 'https://www.termsfeed.com/live/ea8a6e63-b72f-4753-8bff-d98d7a640af8'
  terms_conditions: 'https://www.termsfeed.com/live/3392423f-3926-45b3-b8d9-652cd5edbdb5'
